/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2024-11-09T03:24:43.131Z
  3.46.0.6
  
  Standalone prediction code with sample test data for DRFModel named drf_5ac06507_c6e9_40b0_ae60_a25c8f321214

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/drf-5ac06507-c6e9-40b0-ae60-a25c8f321214 > drf_5ac06507_c6e9_40b0_ae60_a25c8f321214.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m drf_5ac06507_c6e9_40b0_ae60_a25c8f321214.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="drf_5ac06507_c6e9_40b0_ae60_a25c8f321214", algorithm="drf")
public class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 13; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_drf_5ac06507_c6e9_40b0_ae60_a25c8f321214.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* ﻿Region */ drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_ColInfo_0.VALUES,
    /* Year  */ null,
    /* Coal (kt CO2 equivalent) */ null,
    /* Natural Gas (kt CO2 equivalent) */ null,
    /* Other Fuels (kt CO2 equivalent) */ null,
    /* Other Emissions */ null,
    /* Coal (GWh) */ null,
    /* Natural Gas (GWh) */ null,
    /* Other Fuels (GWh) */ null,
    /* Nuclear (GWh) */ null,
    /* Hydro (GWh) */ null,
    /* Other Renewables (GWh) */ null,
    /* Other Generation (GWh) */ null,
    /* CO2 intensity (g CO2 / kWh) */ null,
    /* Generation Intensity (g CO2 eq / kWh) */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public drf_5ac06507_c6e9_40b0_ae60_a25c8f321214() { super(NAMES,DOMAINS,"Generation Intensity (g CO2 eq / kWh)"); }
  public String getUUID() { return Long.toString(-4967748816739691632L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_0.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_1.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_2.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_3.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_4.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_5.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_6.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_7.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_8.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_9.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_10.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_11.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_12.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_13.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_14.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_15.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_16.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_17.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_18.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_19.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_20.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_21.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_22.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_23.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_24.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_25.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_26.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_27.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_28.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_29.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_30.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_31.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_32.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_33.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_34.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_35.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_36.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_37.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_38.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_39.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_40.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_41.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_42.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_43.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_44.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_45.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_46.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_47.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_48.score0(data,preds);
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_49.score0(data,preds);
    preds[0] /= 50;
    return preds;
  }
}
// The class representing training column names
class NamesHolder_drf_5ac06507_c6e9_40b0_ae60_a25c8f321214 implements java.io.Serializable {
  public static final String[] VALUES = new String[13];
  static {
    NamesHolder_drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_0.fill(VALUES);
  }
  static final class NamesHolder_drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "﻿Region";
      sa[1] = "Year ";
      sa[2] = "Coal (kt CO2 equivalent)";
      sa[3] = "Natural Gas (kt CO2 equivalent)";
      sa[4] = "Other Fuels (kt CO2 equivalent)";
      sa[5] = "Other Emissions";
      sa[6] = "Coal (GWh)";
      sa[7] = "Natural Gas (GWh)";
      sa[8] = "Other Fuels (GWh)";
      sa[9] = "Nuclear (GWh)";
      sa[10] = "Hydro (GWh)";
      sa[11] = "Other Renewables (GWh)";
      sa[12] = "Other Generation (GWh)";
    }
  }
}
// The class representing column ﻿Region
class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_ColInfo_0 implements java.io.Serializable {
  public static final String[] VALUES = new String[13];
  static {
    drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_ColInfo_0_0.fill(VALUES);
  }
  static final class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_ColInfo_0_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "AB";
      sa[1] = "BC";
      sa[2] = "MB";
      sa[3] = "NB";
      sa[4] = "NL";
      sa[5] = "NS";
      sa[6] = "NT";
      sa[7] = "NU";
      sa[8] = "ON";
      sa[9] = "PE";
      sa[10] = "QC";
      sa[11] = "SK";
      sa[12] = "YT";
    }
  }
}

class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_0_class_0.score0(fdata);
  }
}
class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
         (data[6 /* Coal (GWh) */] < 1066.8945f ? 
             (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                 (Double.isNaN(data[0 /* ﻿Region */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (data[0] >= 13) || (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                     (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 1269.5312f ? 
                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 39.67285f ? 
                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2014.0f ? 
                                 (data[1 /* Year  */] < 2002.5f ? 
                                    33.0f : 
                                     (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 4.4f ? 
                                         (data[8 /* Other Fuels (GWh) */] < 1023.0f ? 
                                             (data[11 /* Other Renewables (GWh) */] < 100.0f ? 
                                                15.0f : 
                                                18.0f) : 
                                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1317.875f ? 
                                                 (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1208.2781f ? 
                                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2011.0f ? 
                                                        22.0f : 
                                                        21.0f) : 
                                                    26.0f) : 
                                                20.0f)) : 
                                         (data[10 /* Hydro (GWh) */] < 35060.5f ? 
                                            5.9f : 
                                            9.8f))) : 
                                 (data[4 /* Other Fuels (kt CO2 equivalent) */] < 726.0f ? 
                                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 261.9f ? 
                                         (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 236.90999f ? 
                                             (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 14.4f ? 
                                                 (data[8 /* Other Fuels (GWh) */] < 1083.0f ? 
                                                    1.1f : 
                                                    1.2f) : 
                                                1.3f) : 
                                            1.3f) : 
                                        1.5f) : 
                                     (data[8 /* Other Fuels (GWh) */] < 1442.0f ? 
                                        26.0f : 
                                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 38090.5f ? 
                                            40.0f : 
                                            37.0f)))) : 
                             (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[0])) ? 
                                 (data[9 /* Nuclear (GWh) */] < 4810.5f ? 
                                    2.7f : 
                                    3.6f) : 
                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 12.8f ? 
                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2016.5f ? 
                                         (Double.isNaN(data[0 /* ﻿Region */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (data[0] >= 13) || (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT4, 32, 0, data[0])) ? 
                                             (data[1 /* Year  */] < 2012.5f ? 
                                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 6.9725f ? 
                                                    15.0f : 
                                                    12.2f) : 
                                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 24.5f ? 
                                                    16.0f : 
                                                    14.4f)) : 
                                            15.0f) : 
                                        11.692594f) : 
                                    1.9f))) : 
                         (Double.isNaN(data[1]) || data[1 /* Year  */] < 2016.5f ? 
                             (Double.isNaN(data[9]) || data[9 /* Nuclear (GWh) */] < 91390.5f ? 
                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 3.45f ? 
                                     (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 7934.004f ? 
                                        38.0f : 
                                        37.0f) : 
                                     (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 1815.5f ? 
                                        32.0f : 
                                        30.0f)) : 
                                 (data[8 /* Other Fuels (GWh) */] < 721.0f ? 
                                    41.0f : 
                                    42.0f)) : 
                             (data[11 /* Other Renewables (GWh) */] < 12580.0f ? 
                                17.0f : 
                                27.0f))) : 
                    112.13866f) : 
                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 75.625f ? 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 255.5f ? 
                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 0.790625f ? 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 76.325f ? 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2013.0f ? 
                                    200.0f : 
                                    180.0f) : 
                                200.0f) : 
                             (data[7 /* Natural Gas (GWh) */] < 26.225f ? 
                                240.0f : 
                                250.0f)) : 
                        280.0f) : 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 195.5f ? 
                        360.0f : 
                        240.0f))) : 
             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 18066.5f ? 
                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 540.0f ? 
                     (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 5294.8438f ? 
                         (data[1 /* Year  */] < 2006.5f ? 
                            440.0f : 
                             (data[6 /* Coal (GWh) */] < 2441.25f ? 
                                470.0f : 
                                 (data[1 /* Year  */] < 2008.5f ? 
                                    520.0f : 
                                    560.0f))) : 
                        370.0f) : 
                     (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 897.65625f ? 
                        400.0f : 
                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1689.8438f ? 
                            320.0f : 
                            260.0f))) : 
                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 1299.375f ? 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 35574.0f ? 
                        220.0f : 
                        290.0f) : 
                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 124.78125f ? 
                         (data[3 /* Natural Gas (kt CO2 equivalent) */] < 7992.1875f ? 
                            66.0f : 
                            90.0f) : 
                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 35250.5f ? 
                            140.0f : 
                            110.0f))))) : 
         (data[1 /* Year  */] < 2003.0f ? 
             (data[10 /* Hydro (GWh) */] < 722.5f ? 
                1100.0f : 
                 (data[10 /* Hydro (GWh) */] < 1587.0f ? 
                    720.0f : 
                     (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 5.0f ? 
                        950.0f : 
                        850.0f))) : 
             (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 39944.53f ? 
                 (data[6 /* Coal (GWh) */] < 6397.366f ? 
                     (data[7 /* Natural Gas (GWh) */] < 671.875f ? 
                         (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT5, 32, 0, data[0])) ? 
                            167.18233f : 
                            818.46155f) : 
                         (data[1 /* Year  */] < 2013.5f ? 
                             (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 5547.75f ? 
                                 (data[10 /* Hydro (GWh) */] < 890.0f ? 
                                    700.0f : 
                                    720.0f) : 
                                740.0f) : 
                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2020.5f ? 
                                 (data[10 /* Hydro (GWh) */] < 931.5f ? 
                                    680.0f : 
                                    690.0f) : 
                                660.0f))) : 
                     (data[11 /* Other Renewables (GWh) */] < 212.5f ? 
                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 9.609375f ? 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 3605.0f ? 
                                900.0f : 
                                880.0f) : 
                            790.0f) : 
                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 19148.438f ? 
                             (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 336.5f ? 
                                 (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 12210.0f ? 
                                     (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 8852.25f ? 
                                         (data[11 /* Other Renewables (GWh) */] < 502.5f ? 
                                            750.0f : 
                                            760.0f) : 
                                         (data[5 /* Other Emissions */] < 38.95f ? 
                                            660.0f : 
                                            690.0f)) : 
                                    760.0f) : 
                                 (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 4239.5f ? 
                                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 3508.5f ? 
                                         (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 38665.0f ? 
                                            800.0f : 
                                            810.0f) : 
                                        710.0f) : 
                                    840.0f)) : 
                            630.0f))) : 
                 (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 422.46094f ? 
                    930.0f : 
                    870.0f))));
    return pred;
  } // constant pool size = 364B, number of visited nodes = 83, static init size = 180B
  // {10000101 01010000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {-95, 10, 0, 0};
  // {00000010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {64, 0, 0, 0};
  // {00000000 00001000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {0, 16, 0, 0};
  // {11111111 11011000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {-1, 27, 0, 0};
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT4 = new byte[] {4, 0, 0, 0};
  // {00000001 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT5 = new byte[] {-128, 0, 0, 0};
}


class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_1_class_0.score0(fdata);
  }
}
class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
         (data[6 /* Coal (GWh) */] < 1194.9219f ? 
             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 704.10156f ? 
                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2021.5f ? 
                     (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                         (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 68.4375f ? 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 680.0f ? 
                                 (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 14088.0f ? 
                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 20.53125f ? 
                                         (Double.isNaN(data[1]) || data[1 /* Year  */] < 2010.0f ? 
                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 344.0f ? 
                                                49.0f : 
                                                47.0f) : 
                                             (data[10 /* Hydro (GWh) */] < 439.5f ? 
                                                39.0f : 
                                                49.0f)) : 
                                         (data[1 /* Year  */] < 2012.0f ? 
                                            64.0f : 
                                             (data[4 /* Other Fuels (kt CO2 equivalent) */] < 26.5f ? 
                                                69.0f : 
                                                70.0f))) : 
                                     (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 30.75f ? 
                                         (data[10 /* Hydro (GWh) */] < 25493.0f ? 
                                            26.0f : 
                                             (data[6 /* Coal (GWh) */] < 435.0f ? 
                                                32.0f : 
                                                33.0f)) : 
                                         (data[6 /* Coal (GWh) */] < 239.25f ? 
                                            5.9f : 
                                             (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 401.925f ? 
                                                 (data[5 /* Other Emissions */] < 9.955f ? 
                                                    12.0f : 
                                                    13.0f) : 
                                                9.8f)))) : 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2016.5f ? 
                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2014.5f ? 
                                        3.6f : 
                                        3.5f) : 
                                     (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 10.4f ? 
                                        1.3f : 
                                        1.2f))) : 
                            190.0f) : 
                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 1.3125f ? 
                             (data[8 /* Other Fuels (GWh) */] < 71.85016f ? 
                                180.0f : 
                                 (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 585.0f ? 
                                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 73.0f ? 
                                         (data[3 /* Natural Gas (kt CO2 equivalent) */] < 2.04f ? 
                                            190.0f : 
                                            200.0f) : 
                                        240.0f) : 
                                    230.0f)) : 
                             (data[1 /* Year  */] < 2003.0f ? 
                                240.0f : 
                                265.84906f))) : 
                    70.0f) : 
                 (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 131590.5f ? 
                         (data[5 /* Other Emissions */] < 5.6671877f ? 
                             (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 730.0f ? 
                                24.0f : 
                                13.0f) : 
                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2016.5f ? 
                                 (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 2613.5f ? 
                                     (data[10 /* Hydro (GWh) */] < 51163.0f ? 
                                        16.0f : 
                                         (data[12 /* Other Generation (GWh) */] < 1307.0f ? 
                                            14.4f : 
                                            15.0f)) : 
                                    12.2f) : 
                                 (data[1 /* Year  */] < 2017.5f ? 
                                    10.6f : 
                                     (data[1 /* Year  */] < 2019.0f ? 
                                        14.5f : 
                                         (data[1 /* Year  */] < 2021.0f ? 
                                            12.6f : 
                                            13.500001f))))) : 
                         (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 418.59375f ? 
                             (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 1.395f ? 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2014.0f ? 
                                     (data[9 /* Nuclear (GWh) */] < 1789.5f ? 
                                        2.0f : 
                                         (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 1360.0f ? 
                                            2.7f : 
                                            2.5f)) : 
                                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 263.75f ? 
                                         (data[11 /* Other Renewables (GWh) */] < 8062.5f ? 
                                            1.1f : 
                                            1.2f) : 
                                        1.5f)) : 
                                 (data[1 /* Year  */] < 2003.0f ? 
                                    3.6f : 
                                    3.8f)) : 
                            5.8f)) : 
                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 1414.375f ? 
                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 11171.875f ? 
                             (data[1 /* Year  */] < 2013.5f ? 
                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 941.39374f ? 
                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 715.34845f ? 
                                        15.0f : 
                                         (data[1 /* Year  */] < 2010.0f ? 
                                            22.0f : 
                                             (data[8 /* Other Fuels (GWh) */] < 1050.5762f ? 
                                                20.0f : 
                                                21.0f))) : 
                                    26.0f) : 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2021.0f ? 
                                     (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 13.5f ? 
                                         (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 2232.5f ? 
                                             (data[1 /* Year  */] < 2016.0f ? 
                                                30.0f : 
                                                 (data[1 /* Year  */] < 2018.5f ? 
                                                    26.0f : 
                                                    27.0f)) : 
                                            27.0f) : 
                                        29.0f) : 
                                    17.0f)) : 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 842.6914f ? 
                                42.0f : 
                                37.0f)) : 
                        45.0f))) : 
             (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 296.5039f ? 
                 (data[2 /* Coal (kt CO2 equivalent) */] < 1496.0938f ? 
                     (data[10 /* Hydro (GWh) */] < 3650.5f ? 
                        370.0f : 
                        400.0f) : 
                     (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 334.21875f ? 
                         (Double.isNaN(data[1]) || data[1 /* Year  */] < 2008.5f ? 
                             (data[12 /* Other Generation (GWh) */] < 213.5f ? 
                                490.0f : 
                                520.0f) : 
                            560.0f) : 
                        470.0f)) : 
                 (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 1298.5f ? 
                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 410.625f ? 
                        220.0f : 
                         (data[7 /* Natural Gas (GWh) */] < 1523.4375f ? 
                            330.0f : 
                             (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 19980.0f ? 
                                 (Double.isNaN(data[9]) || data[9 /* Nuclear (GWh) */] < 4655.5f ? 
                                    300.0f : 
                                    260.0f) : 
                                290.0f))) : 
                     (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 3718.75f ? 
                         (data[4 /* Other Fuels (kt CO2 equivalent) */] < 182.5f ? 
                            140.0f : 
                            170.0f) : 
                         (data[7 /* Natural Gas (GWh) */] < 15742.1875f ? 
                            66.0f : 
                            90.0f))))) : 
         (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 42771.094f ? 
             (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 19121.484f ? 
                 (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 2816.4062f ? 
                     (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[0])) ? 
                         (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 425.0f ? 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 201.325f ? 
                                 (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 6.84f ? 
                                     (data[1 /* Year  */] < 2006.0f ? 
                                        120.0f : 
                                        130.0f) : 
                                    230.0f) : 
                                19.0f) : 
                            13.97561f) : 
                         (data[2 /* Coal (kt CO2 equivalent) */] < 2437.5f ? 
                             (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 550.5f ? 
                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 26.25f ? 
                                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 152.215f ? 
                                         (data[6 /* Coal (GWh) */] < 4920.0f ? 
                                            760.13336f : 
                                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2006.0f ? 
                                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 58.0f ? 
                                                    800.0f : 
                                                    790.0f) : 
                                                 (data[7 /* Natural Gas (GWh) */] < 2761.25f ? 
                                                    760.0f : 
                                                    770.0f))) : 
                                        820.6135f) : 
                                    840.0f) : 
                                710.0f) : 
                             (data[1 /* Year  */] < 2011.5f ? 
                                 (data[7 /* Natural Gas (GWh) */] < 695.0f ? 
                                    720.0f : 
                                     (data[2 /* Coal (kt CO2 equivalent) */] < 6093.75f ? 
                                        740.0f : 
                                         (data[6 /* Coal (GWh) */] < 7780.0f ? 
                                            750.0f : 
                                            790.0f))) : 
                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 2720.0f ? 
                                     (data[8 /* Other Fuels (GWh) */] < 563.4412f ? 
                                         (data[7 /* Natural Gas (GWh) */] < 8672.25f ? 
                                            660.0f : 
                                            680.0741f) : 
                                        690.05817f) : 
                                    760.0f)))) : 
                     (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 3635.0085f ? 
                        940.0f : 
                        880.0f)) : 
                 (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 26830.371f ? 
                    580.0f : 
                    510.0f)) : 
             (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 46947.957f ? 
                970.0f : 
                930.0f)));
    return pred;
  } // constant pool size = 426B, number of visited nodes = 101, static init size = 120B
  // {10000101 01010000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {-95, 10, 0, 0};
  // {00010010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {72, 0, 0, 0};
  // {00001000 10000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {16, 1, 0, 0};
  // {11111111 10111000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {-1, 29, 0, 0};
}


class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_2_class_0.score0(fdata);
  }
}
class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
         (data[6 /* Coal (GWh) */] < 1066.8945f ? 
             (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                 (data[10 /* Hydro (GWh) */] < 10117.5f ? 
                     (data[10 /* Hydro (GWh) */] < 414.5f ? 
                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 335.0f ? 
                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2002.5f ? 
                                71.0f : 
                                64.0f) : 
                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 394.0f ? 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2009.0f ? 
                                    47.0f : 
                                    44.0f) : 
                                38.0f)) : 
                         (data[1 /* Year  */] < 2001.5f ? 
                            190.0f : 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 0.25f ? 
                                 (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 25.6105f ? 
                                    70.0f : 
                                    69.0f) : 
                                 (data[1 /* Year  */] < 2017.0f ? 
                                    39.0f : 
                                    70.0f)))) : 
                     (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 6.5625f ? 
                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 103024.5f ? 
                             (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 47.5f ? 
                                 (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1442.0f ? 
                                     (data[8 /* Other Fuels (GWh) */] < 727.0f ? 
                                         (Double.isNaN(data[0 /* ﻿Region */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (data[0] >= 13) || (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                                             (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 609.0f ? 
                                                 (data[12 /* Other Generation (GWh) */] < 11.0f ? 
                                                    26.0f : 
                                                    29.0f) : 
                                                33.0f) : 
                                            38.0f) : 
                                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 6.234375f ? 
                                             (data[4 /* Other Fuels (kt CO2 equivalent) */] < 113.0f ? 
                                                 (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 51793.0f ? 
                                                     (data[8 /* Other Fuels (GWh) */] < 885.25f ? 
                                                        26.0f : 
                                                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 5.2992187f ? 
                                                            33.0f : 
                                                            30.0f)) : 
                                                    24.0f) : 
                                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 926.6f ? 
                                                     (data[10 /* Hydro (GWh) */] < 38400.5f ? 
                                                        27.0f : 
                                                         (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 765.27997f ? 
                                                             (data[1 /* Year  */] < 2008.0f ? 
                                                                15.0f : 
                                                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 718.384f ? 
                                                                    17.0f : 
                                                                    18.0f)) : 
                                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 40441.0f ? 
                                                                20.0f : 
                                                                19.0f))) : 
                                                    26.0f)) : 
                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 54205.5f ? 
                                                15.0f : 
                                                10.6f))) : 
                                     (data[8 /* Other Fuels (GWh) */] < 1685.0f ? 
                                        31.571428f : 
                                         (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 95.0f ? 
                                            45.0f : 
                                            40.0f))) : 
                                42.0f) : 
                             (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 463.5f ? 
                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 1.4765625f ? 
                                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 172704.5f ? 
                                         (Double.isNaN(data[9]) || data[9 /* Nuclear (GWh) */] < 3913.0f ? 
                                             (data[5 /* Other Emissions */] < 0.23f ? 
                                                2.5f : 
                                                2.6f) : 
                                            2.7f) : 
                                         (data[11 /* Other Renewables (GWh) */] < 3740.0f ? 
                                            2.0f : 
                                             (data[1 /* Year  */] < 2016.5f ? 
                                                1.1f : 
                                                1.2f))) : 
                                     (data[3 /* Natural Gas (kt CO2 equivalent) */] < 231.75f ? 
                                        3.6f : 
                                        3.8f)) : 
                                5.8f)) : 
                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 563.28125f ? 
                             (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 13.876562f ? 
                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 680.0f ? 
                                     (data[6 /* Coal (GWh) */] < 239.25f ? 
                                        5.9f : 
                                         (data[1 /* Year  */] < 2006.5f ? 
                                             (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 18.0f ? 
                                                12.0f : 
                                                9.8f) : 
                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 34080.5f ? 
                                                15.0f : 
                                                13.0f))) : 
                                    3.5f) : 
                                 (data[1 /* Year  */] < 2015.0f ? 
                                    3.2999997f : 
                                     (data[1 /* Year  */] < 2017.5f ? 
                                        1.9f : 
                                        1.3f))) : 
                             (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 463.5f ? 
                                16.0f : 
                                13.500001f)))) : 
                252.75133f) : 
             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1689.8438f ? 
                 (data[4 /* Other Fuels (kt CO2 equivalent) */] < 410.625f ? 
                     (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 20346.875f ? 
                         (Double.isNaN(data[9]) || data[9 /* Nuclear (GWh) */] < 87182.0f ? 
                             (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 10.5f ? 
                                140.0f : 
                                110.0f) : 
                            66.0f) : 
                        220.0f) : 
                     (data[2 /* Coal (kt CO2 equivalent) */] < 897.65625f ? 
                        400.0f : 
                         (data[9 /* Nuclear (GWh) */] < 4121.5f ? 
                            330.0f : 
                             (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 0.385f ? 
                                 (data[4 /* Other Fuels (kt CO2 equivalent) */] < 1350.6094f ? 
                                    290.0f : 
                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2016.5f ? 
                                         (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 1789.5f ? 
                                            310.0f : 
                                            300.0f) : 
                                        320.0f)) : 
                                290.0f)))) : 
                 (data[10 /* Hydro (GWh) */] < 3095.5f ? 
                    560.0f : 
                     (data[1 /* Year  */] < 1999.0f ? 
                        370.0f : 
                         (data[2 /* Coal (kt CO2 equivalent) */] < 1196.875f ? 
                            400.0f : 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 207.0f ? 
                                520.0f : 
                                470.0f)))))) : 
         (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 31985.742f ? 
             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 690.625f ? 
                 (data[8 /* Other Fuels (GWh) */] < 32.30781f ? 
                     (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[0])) ? 
                         (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 258.98438f ? 
                            125.2f : 
                             (data[8 /* Other Fuels (GWh) */] < 5.992117f ? 
                                 (data[8 /* Other Fuels (GWh) */] < 1.4669088f ? 
                                    2.0f : 
                                     (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 617.5f ? 
                                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 3.2167816f ? 
                                            3.0f : 
                                            2.5f) : 
                                        4.0f)) : 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2013.5f ? 
                                    8.0f : 
                                    7.0f))) : 
                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 32.8125f ? 
                             (data[1 /* Year  */] < 2008.5f ? 
                                710.0f : 
                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 618.75f ? 
                                     (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 545.34375f ? 
                                        810.0f : 
                                        800.0f) : 
                                    840.0f)) : 
                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 4579.5f ? 
                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 11.185f ? 
                                     (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 39.95f ? 
                                        700.0f : 
                                        690.0f) : 
                                    710.0f) : 
                                760.0f))) : 
                     (data[8 /* Other Fuels (GWh) */] < 127.87872f ? 
                        1100.0f : 
                         (data[1 /* Year  */] < 1995.5f ? 
                            720.0f : 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 287.0f ? 
                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 172.2f ? 
                                     (data[1 /* Year  */] < 2006.0f ? 
                                         (data[1 /* Year  */] < 2002.5f ? 
                                            830.0f : 
                                            880.0f) : 
                                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 924.303f ? 
                                            807.1875f : 
                                            790.0f)) : 
                                    940.0f) : 
                                750.0f)))) : 
                 (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 25390.625f ? 
                     (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 10145.776f ? 
                         (data[6 /* Coal (GWh) */] < 4648.4375f ? 
                            660.0f : 
                             (data[1 /* Year  */] < 2013.5f ? 
                                 (data[6 /* Coal (GWh) */] < 5451.172f ? 
                                    700.0f : 
                                    720.0f) : 
                                 (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT4, 32, 0, data[0])) ? 
                                    670.0f : 
                                    690.0f))) : 
                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 3180.0f ? 
                            630.0f : 
                            580.0f)) : 
                     (data[2 /* Coal (kt CO2 equivalent) */] < 11781.25f ? 
                        470.0f : 
                        510.0f))) : 
             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 1965.625f ? 
                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 1090.3076f ? 
                     (data[3 /* Natural Gas (kt CO2 equivalent) */] < 3753.9062f ? 
                        950.0f : 
                        970.0f) : 
                     (data[8 /* Other Fuels (GWh) */] < 513.925f ? 
                        870.0f : 
                        880.0f)) : 
                 (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 38732.605f ? 
                    800.0f : 
                    760.0f))));
    return pred;
  } // constant pool size = 447B, number of visited nodes = 105, static init size = 150B
  // {10000101 01010000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {-95, 10, 0, 0};
  // {00000010 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {64, 0, 0, 0};
  // {01000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {2, 0, 0, 0};
  // {00000000 00010000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {0, 8, 0, 0};
  // {00000100 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT4 = new byte[] {32, 0, 0, 0};
}


class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_3_class_0.score0(fdata);
  }
}
class drf_5ac06507_c6e9_40b0_ae60_a25c8f321214_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[9]) || data[9 /* Nuclear (GWh) */] < 234.5f ? 
         (data[1 /* Year  */] < 2003.0f ? 
             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 136.6292f ? 
                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 45.625f ? 
                     (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
                        33.0f : 
                         (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 850.0f ? 
                             (data[1 /* Year  */] < 1995.0f ? 
                                800.0f : 
                                850.0f) : 
                            950.0f)) : 
                     (data[8 /* Other Fuels (GWh) */] < 64.72527f ? 
                        1100.0f : 
                        1300.0f)) : 
                 (data[6 /* Coal (GWh) */] < 4516.797f ? 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 17626.5f ? 
                        240.0f : 
                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1540.6145f ? 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 820.1536f ? 
                                38.0f : 
                                19.0f) : 
                            45.0f)) : 
                    830.0f)) : 
             (data[7 /* Natural Gas (GWh) */] < 126.953125f ? 
                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2019.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 91.25f ? 
                         (data[4 /* Other Fuels (kt CO2 equivalent) */] < 2.8515625f ? 
                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2007.5f ? 
                                265.84906f : 
                                 (data[8 /* Other Fuels (GWh) */] < 33.5125f ? 
                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 1.425f ? 
                                        2.5f : 
                                         (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 32.5f ? 
                                            4.0f : 
                                            3.2999997f)) : 
                                    200.0f)) : 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 53.2125f ? 
                                 (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 11.31f ? 
                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2006.5f ? 
                                         (data[1 /* Year  */] < 2005.5f ? 
                                            120.0f : 
                                            230.0f) : 
                                         (data[4 /* Other Fuels (kt CO2 equivalent) */] < 5.0115f ? 
                                             (Double.isNaN(data[1]) || data[1 /* Year  */] < 2014.5f ? 
                                                8.0f : 
                                                7.0f) : 
                                            130.0f)) : 
                                     (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 10.465f ? 
                                         (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 19.5f ? 
                                             (data[8 /* Other Fuels (GWh) */] < 23.7f ? 
                                                38.0f : 
                                                 (data[4 /* Other Fuels (kt CO2 equivalent) */] < 17.366251f ? 
                                                     (data[11 /* Other Renewables (GWh) */] < 0.4975f ? 
                                                        47.0f : 
                                                        49.0f) : 
                                                     (data[11 /* Other Renewables (GWh) */] < 0.07125f ? 
                                                        49.0f : 
                                                         (Double.isNaN(data[1]) || data[1 /* Year  */] < 2011.0f ? 
                                                            44.0f : 
                                                            39.0f)))) : 
                                             (data[6 /* Coal (GWh) */] < 186.225f ? 
                                                 (data[8 /* Other Fuels (GWh) */] < 15.6f ? 
                                                    3.5f : 
                                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2013.0f ? 
                                                        2.7f : 
                                                        1.8f)) : 
                                                 (data[1 /* Year  */] < 2006.5f ? 
                                                    12.0f : 
                                                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 34050.5f ? 
                                                        15.0f : 
                                                        13.0f)))) : 
                                         (data[3 /* Natural Gas (kt CO2 equivalent) */] < 21.15425f ? 
                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 16652.0f ? 
                                                69.0f : 
                                                1.2f) : 
                                            100.0f))) : 
                                 (data[8 /* Other Fuels (GWh) */] < 89.47282f ? 
                                    200.0f : 
                                    240.0f))) : 
                         (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                             (Double.isNaN(data[4]) || data[4 /* Other Fuels (kt CO2 equivalent) */] < 1242.25f ? 
                                 (data[4 /* Other Fuels (kt CO2 equivalent) */] < 932.575f ? 
                                     (Double.isNaN(data[1]) || data[1 /* Year  */] < 2012.5f ? 
                                         (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 1130.3733f ? 
                                            18.0f : 
                                            20.0f) : 
                                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 7.0f ? 
                                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 9741.5f ? 
                                                 (data[1 /* Year  */] < 2015.5f ? 
                                                    1.1f : 
                                                    1.2f) : 
                                                1.3f) : 
                                            2.0f)) : 
                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 1088.1438f ? 
                                        26.0f : 
                                         (data[1 /* Year  */] < 2018.5f ? 
                                            26.0f : 
                                            27.0f))) : 
                                 (data[1 /* Year  */] < 2016.0f ? 
                                    33.0f : 
                                    40.0f)) : 
                            750.0f)) : 
                     (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                         (Double.isNaN(data[1]) || data[1 /* Year  */] < 2020.5f ? 
                            180.0f : 
                             (data[4 /* Other Fuels (kt CO2 equivalent) */] < 438.0f ? 
                                 (!Double.isNaN(data[0 /* ﻿Region */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[0])) ? 
                                     (data[8 /* Other Fuels (GWh) */] < 1233.119f ? 
                                        1.2f : 
                                        1.3f) : 
                                     (Double.isNaN(data[0 /* ﻿Region */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (data[0] >= 13) || (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 13) && !GenModel.bitSetContains(GRPSPLIT4, 32, 0, data[0])) ? 
                                         (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 14.4f ? 
                                            1.9f : 
                                            1.3f) : 
                                        2.0f)) : 
                                17.0f)) : 
                        775.06494f)) : 
                 (data[6 /* Coal (GWh) */] < 3926.1719f ? 
                     (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 24570.5f ? 
                         (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 3645.5f ? 
                             (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 333.0f ? 
                                560.0f : 
                                470.0f) : 
                            400.0f) : 
                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 1374.0625f ? 
                             (data[10 /* Hydro (GWh) */] < 53393.5f ? 
                                 (data[10 /* Hydro (GWh) */] < 51513.0f ? 
                                    16.0f : 
                                     (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 779.9219f ? 
                                        14.5f : 
                                        14.4f)) : 
                                 (data[7 /* Natural Gas (GWh) */] < 574.2578f ? 
                                    10.6f : 
                                     (Double.isNaN(data[3]) || data[3 /* Natural Gas (kt CO2 equivalent) */] < 733.5f ? 
                                         (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 697.5f ? 
                                            12.6f : 
                                            12.2f) : 
                                        13.500001f))) : 
                            30.0f)) : 
                     (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 39971.203f ? 
                         (data[7 /* Natural Gas (GWh) */] < 1041.7358f ? 
                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 3596.2712f ? 
                                940.0f : 
                                880.0f) : 
                             (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 19474.607f ? 
                                 (Double.isNaN(data[12]) || data[12 /* Other Generation (GWh) */] < 336.5f ? 
                                     (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 36.9f ? 
                                         (data[11 /* Other Renewables (GWh) */] < 438.4f ? 
                                            790.0f : 
                                             (Double.isNaN(data[8]) || data[8 /* Other Fuels (GWh) */] < 850.5935f ? 
                                                 (Double.isNaN(data[5]) || data[5 /* Other Emissions */] < 26.25f ? 
                                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 6.8f ? 
                                                        760.0f : 
                                                        770.0f) : 
                                                    760.0f) : 
                                                 (Double.isNaN(data[11]) || data[11 /* Other Renewables (GWh) */] < 962.35f ? 
                                                     (Double.isNaN(data[7]) || data[7 /* Natural Gas (GWh) */] < 2062.0f ? 
                                                        720.0f : 
                                                        700.0f) : 
                                                     (data[11 /* Other Renewables (GWh) */] < 1331.6613f ? 
                                                        690.0f : 
                                                        680.0f)))) : 
                                         (data[7 /* Natural Gas (GWh) */] < 8090.4775f ? 
                                            700.0f : 
                                             (Double.isNaN(data[10]) || data[10 /* Hydro (GWh) */] < 3735.5f ? 
                                                 (Double.isNaN(data[6]) || data[6 /* Coal (GWh) */] < 10180.0f ? 
                                                     (data[4 /* Other Fuels (kt CO2 equivalent) */] < 5.695f ? 
                                                        660.0f : 
                                                        670.0f) : 
                                                    690.0f) : 
                                                660.0f))) : 
                                     (data[6 /* Coal (GWh) */] < 11978.24f ? 
                                        840.0f : 
                                         (Double.isNaN(data[2]) || data[2 /* Coal (kt CO2 equivalent) */] < 38665.0f ? 
                                            800.0f : 
                                            810.0f))) : 
                                 (Double.isNaN(data[1]) || data[1 /* Year  */] < 2019.5f ? 
                                    630.0f : 